#!/bin/sh
# Copyright (C) 2018 Wesley Tanaka
#
# This file is part of docker-alpine-37-uid-npm
#
# docker-alpine-37-uid-npm is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# docker-alpine-37-uid-npm is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with docker-alpine-37-uid-npm.  If not, see
# <http://www.gnu.org/licenses/>.

# Use this script to launch a command line program inside the
# container, e.g.

# Use /usr/bin/npm explicitly to avoid it resolving to $HOME/bin/npm
# inside the container if this script is put in $HOME/bin/ outside the
# container
exec docker run \
  -i -t --rm \
  -e "HOSTUID=`id -u`" \
  -e "HOSTGID=`id -g`" \
  -v "`pwd`:/work" \
  -v "$HOME:/home/hostuser" \
  wtanaka/alpine-37-uid-npm \
  /usr/bin/node "$@"
